services:
  autodns:
    image: ghcr.io/baker-scripts/autodns:develop
    ports:
    - "4295:4295"
    volumes:
    - "/your/path/to/config:/config"
    environment:
      - "CF_ZONE_ID=your-zone-id"
      - "CF_API_TOKEN=your-api-token"
      - "APPRISE_URLS=your-apprise-urls-separated-by-commas"
      - "AUTODNS_PORT=4295"
      - "AUTODNS_HOST=0.0.0.0"
      - "TRUSTED_PROXIES="
    restart: unless-stopped
