# Use an updated and specific version of the Python image
FROM python:3.11-slim-bullseye

# Define work directory
WORKDIR /app

# Set Python to not generate .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Set Python stdout and stderr streams to be unbuffered
ENV PYTHONUNBUFFERED=1

# Set Flask application port
ENV FLASK_RUN_PORT=4295

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libffi-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Update pip and install dependencies via wheel to speed up installation
RUN python -m pip install --upgrade pip setuptools wheel

# Copy only the requirements file to leverage Docker cache
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Specify non-root user to run the app
RUN useradd -m myuser
USER myuser

# Expose the port the app runs on
EXPOSE 4295

# Command to run the application
CMD ["python", "./autodns.py"]
