name: Docker Image CI

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          TAG="ghcr.io/${{ github.repository_owner }}/autodns"
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            IMAGE_TAG="latest"
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            IMAGE_TAG="develop"
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            IMAGE_TAG="${{ github.ref_name }}"
          fi
          FULL_TAG="${TAG}:${IMAGE_TAG}"
          echo "Building and pushing Docker image with tag $FULL_TAG"
          docker build . --file Dockerfile --tag $FULL_TAG
          docker push $FULL_TAG
